# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='coverimage_location',
            field=models.CharField(max_length=1000),
        ),
    ]
