# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20160410_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_directory',
            field=models.FilePathField(default=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
